spring:
  application:
    name: smart_wallet_service

  datasource:
    url: jdbc:postgresql://192.168.68.111:5432/smart_wallet
    username: admin
    password: adminA@1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: vuhoaianh38@gmail.com
    password: jnlb iluy cltk xwix
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: smart-wallet-secret-key-smart-wallet-smart-wallet
  expiration: 36000000

app:
  baseUrl: https://2ca6-14-160-26-144.ngrok-free.app

vnpay:
  tmnCode: T8I9WSZS
  secretKey: 1G49FUKT7DZRYKB6J0JW7R6BCZ9ESMO5
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: ${app.baseUrl}/api/v1/payment-transaction/vnpay-return
  ipnUrl: ${app.baseUrl}/api/v1/payment-transaction/vnpay-ipn

  version: 2.1.0
  command: pay
  currCode: VND
  locale: vn
  orderType: other
  orderInfo: Nang cap prenium

  successCode: "00"

  ipnResponseCodeHandled: "00"
  ipnResponseCodeInvalidRequest: "99"
  ipnResponseCodeInvalidChecksum: "97"

  ipnMessageConfirmSuccess: Confirm Success
  ipnMessageConfirmFailed: Confirm Failed
  ipnMessageInvalidRequest: Invalid request
  ipnMessageInvalidChecksum: Invalid Checksum

  returnMessageSuccess: Payment success
  returnMessageFailed: Payment failed
  returnMessageInvalidRequest: Invalid request
  returnMessageInvalidChecksum: Invalid checksum
