package com.minhpt.smart_wallet_service.constant;

public class Constant {
    public static final String USER_DEFAULT = "system";
    public static final String SUCCESS = "Thành công";
    public static final String ROLE_USER = "ROLE_USER";
    public static final String ROLE_ADMIN = "ROLE_ADMIN";
    public static final int DELETED = 0;
    public static final int NOT_DELETE = 1;
    public static final int VERIFIED = 1;
    public static final int NOT_VERIFIED = 0;
    public static final int NOT_PREMIUM = 0;
    public static final int USED = 1;
    public static final int NOT_USED = 0;
    public static final String ACTIVE = "ACTIVE";
    public static final String VNPAY = "VNPAY";
    public static final String MOMO = "MOMO";
    public static final String STATE_PENDING = "PENDING";
    public static final String STATE_SUCCESS = "SUCCESS";
    public static final String STATE_FAILED = "FAILED";
    public static final int PREMIUM = 1;
    public static final String SCHEDULE_ACTION_TRANSACTION = "TRANSACTION";
    public static final String SCHEDULE_ACTION_GOAL_DEPOSIT = "GOAL_DEPOSIT";
    public static final String SCHEDULE_FREQUENCY_DAILY = "DAILY";
    public static final String SCHEDULE_FREQUENCY_WEEKLY = "WEEKLY";
    public static final String SCHEDULE_FREQUENCY_MONTHLY = "MONTHLY";
    public static final String SCHEDULE_STATE_PENDING = "PENDING";
    public static final String SCHEDULE_STATE_PROCESSING = "PROCESSING";
    public static final String SCHEDULE_STATE_SUCCESS = "SUCCESS";
    public static final String SCHEDULE_STATE_FAILED = "FAILED";
    public static final String SCHEDULE_STATE_CANCELED = "CANCELED";
    public static final String SCHEDULE_STATE_COMPLETED = "COMPLETED";
    public static final String SCHEDULE_EXECUTION_SUCCESS = "SUCCESS";
    public static final String SCHEDULE_EXECUTION_FAILED = "FAILED";
    public static final String NOTIFICATION_TARGET_ALL = "ALL";
    public static final String NOTIFICATION_TARGET_PREMIUM = "PREMIUM";
    public static final String NOTIFICATION_TARGET_FREE = "FREE";
    public static final String NOTIFICATION_RECURRENCE_ONCE = "ONCE";
    public static final String NOTIFICATION_RECURRENCE_DAILY = "DAILY";
    public static final String NOTIFICATION_RECURRENCE_WEEKLY = "WEEKLY";
    public static final String NOTIFICATION_RECURRENCE_MONTHLY = "MONTHLY";
}
